ContosoUniversity/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}

ContosoUniversity/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public enum Grade
    {
        A, B, C, D, F
    }

    public class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public Grade? Grade { get; set; }

        public Course Course { get; set; }
        public Student Student { get; set; }
    }
}

ContosoUniversity/Models/ErrorViewModel.cs
using System;

namespace ContosoUniversity.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContosoUniversity/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class Student
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}

ContosoUniversity/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Controllers
{
    public class CoursesController : Controller
    {

        private readonly SchoolContext _context;

        public CoursesController(SchoolContext context)
        {
            _context = context;
        }
        // GET: Students
        public IActionResult Index() {
            return View();
        }

        public IActionResult List() {
            return Json(_context.Courses);
        }
    }
}

ContosoUniversity/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ContosoUniversity.Data;
using ContosoUniversity.Data;
using ContosoUniversity.Helper;

namespace ContosoUniversity.Controllers
{
    public class DepartmentsController : Controller
    {
        private SchoolContext _context;

        public DepartmentsController(SchoolContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List() {
            return Json(_context.Students);
        }
    }
}

ContosoUniversity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ContosoUniversity.Models;

namespace ContosoUniversity.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContosoUniversity/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SchoolContext _context;

        public StudentsController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Students
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Students.ToListAsync());
        //}

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult List()
        {

            return Json(_context.Students);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost,ActionName("Save")]
        [ValidateAntiForgeryToken]
        public IActionResult Add([Bind("EnrollmentDate,FirstMidName,LastName")]
        Student student)
        {
            Dictionary<string, object> dic = new Dictionary<string, object>();
            dic.Add("errcode", 0);
            dic.Add("errmsg", "ok");
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(student);
                    _context.SaveChangesAsync();
                    //return RedirectToAction(nameof(Index));
                }
                else {
                    dic["errcode"] = 1;
                    dic["errmsg"] = "ModelState.IsValid fail";
                }
            }
            catch(DbUpdateException ex){
                dic["errcode"] = -1;
                dic["errmsg"] = "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.";
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return Json(dic);
        }

        public IActionResult Edit(int id) {
            Student student = _context.Students.Where(p => p.ID.Equals(id)).First();
            return View(student);
        }

        public IActionResult Update(Student student) {
            return Json("");
        }
    }
}

ContosoUniversity/Views/Courses/Index.cshtml
@model IEnumerable<ContosoUniversity.Models.Course>
@{
    ViewData["Title"] = "Index";
}

<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">@ViewData["Title"]</div>
        <div class="layui-card-body">
            <div class="layui-btn-group">
                <button class="layui-btn">增加</button>
                <button class="layui-btn">编辑</button>
                <button class="layui-btn">删除</button>
            </div>
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        layui.use('table', function () {
            var table = layui.table;

            //第一个实例
            table.render({
                elem: '#demo',
                height: 312,
                url: '/Courses/List', //数据接口
                parseData: function (res) { //res 即为原始返回的数据
                    return {
                        "code": 0, //解析接口状态
                        "msg": '', //解析提示文本
                        "count": res.length, //解析数据长度
                        "data": res //解析数据列表
                    };
                },
                page: true, //开启分页
                cols: [[ //表头
                    { field: 'courseID', title: 'ID', width: 80, sort: true, fixed: 'left' },
                    { field: 'title', title: '课程名', width: 150 },
                    { field: 'credits', title: '学分', width: 100, sort: true }
                ]]
            });
    });
});
</script>

ContosoUniversity/Views/Departments/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">@ViewData["Title"]</div>
        <div class="layui-card-body">
            <div class="layui-btn-group">
                <button class="layui-btn">增加</button>
                <button class="layui-btn">编辑</button>
                <button class="layui-btn">删除</button>
            </div>
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        layui.use('table', function () {
            var table = layui.table;

            //第一个实例
            table.render({
                elem: '#demo',
                height: 312,
                url: '/Students/List', //数据接口
                parseData: function (res) { //res 即为原始返回的数据
                    return {
                        "code": 0, //解析接口状态
                        "msg": '', //解析提示文本
                        "count": res.length, //解析数据长度
                        "data": res //解析数据列表
                    };
                },
                page: true, //开启分页
                cols: [[ //表头
                    { field: 'lastName', title: 'ID', width: 80, sort: true, fixed: 'left' },
                    { field: 'firstMidName', title: '用户名', width: 80 },
                    { field: 'enrollmentDate', title: '性别', width: 80, sort: true }
                ]]
            });
    });
});
</script>

ContosoUniversity/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">@ViewData["Title"]</div>
        <div class="layui-card-body">
            <h3>@ViewData["Message"]</h3>
            <p>Use this area to provide additional information.</p>
        </div>
    </div>
</div>

ContosoUniversity/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ContosoUniversity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">@ViewData["Title"]</div>
        <div class="layui-card-body">
            <h2>Welcome to Contoso University</h2>
            <p>
                Contoso University is a sample application that
                demonstrates how to use Entity Framework Core in an
                ASP.NET Core MVC web application.
            </p>
        </div>
    </div>
</div>

ContosoUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContosoUniversity</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Contoso University</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Students" asp-action="Index">Students</a></li>
                    <li><a asp-area="" asp-controller="Courses" asp-action="Index">Courses</a></li>
                    <li><a asp-area="" asp-controller="Instructors" asp-action="Index">Instructors</a></li>
                    <li><a asp-area="" asp-controller="Departments" asp-action="Index">Departments</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Contoso University</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

ContosoUniversity/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - ContosoUniversity</title>
    <link rel="stylesheet" href="~/lib/layui/css/layui.css" />
    <script src="/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="/lib/layui/layui.js" type="text/javascript"></script>
</head>
<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo">ContosoUniversity</div>
            <!-- 头部区域（可配合layui已有的水平导航） -->
            <ul class="layui-nav layui-layout-left">
                <li class="layui-nav-item"><a href="/Home/Index">主页</a></li>
                <li class="layui-nav-item"><a href="/Home/About">关于</a></li>
                <li class="layui-nav-item"><a href="/Students/Index">学生</a></li>
                <li class="layui-nav-item"><a href="/Courses/Index">课程</a></li>
                <li class="layui-nav-item"><a href="/Departments/Index">部门</a></li>
            </ul>
            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item">
                    <a href="javascript:;">
                        <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
                        贤心
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a href="">基本资料</a></dd>
                        <dd><a href="">安全设置</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href="">退出</a></li>
            </ul>
        </div>
        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree" lay-filter="test">
                    <li class="layui-nav-item layui-nav-itemed">
                        <a class="" href="javascript:;">所有学生</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">我创建的学生</a></dd>
                            <dd><a href="javascript:;">我管理的学生</a></dd>
                            <dd><a href="javascript:;">我审批的学生</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">应用配置</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">管理权限</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item"><a href="javascript:;">回收站</a></li>
                </ul>
            </div>
        </div>
        <div class="layui-body">
            <!-- 内容主体区域 -->
            <div style="padding: 15px;">
                @RenderBody()
            </div>
        </div>

        <div class="layui-footer">
            <!-- 底部固定区域 -->
            © ContosoUniversity - 课程管理系统
        </div>
    </div>
</body>
</html>

ContosoUniversity/Views/Students/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="~/lib/layui/css/layui.css">
    <script src="/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="/lib/layui/layui.js" type="text/javascript"></script>
    <script type="text/javascript">
        function layerMsg(msg) {
            layui.use('layer', function () {
                var layer = layui.layer;
                layer.msg(msg);
            });
        }
        function closeLayer() {
            layui.use('layer', function () {
                var layer = layui.layer;
                var index = parent.layer.getFrameIndex(window.name);
                parent.layer.close(index);
            });
        }
        function getParameters() {
            var form = $('#__AjaxAntiForgeryForm');
            var token = $('input[name="__RequestVerificationToken"]', form).val();
            var params = {
                __RequestVerificationToken: token, 
                LastName: $('#lastName').val(),
                FirstMidName: $('#firstMidName').val(),
                EnrollmentDate: $('#enrollmentDate').val()
            };
            return params;
        }
        function saveStudent() {
            $.ajax({
                type: 'post',
                dataType: 'json',
                data: getParameters(),
                url: '/Students/Save',
                success: function (res) {
                    layerMsg('success');
                },
                error: function (res) {
                    layerMsg('请求失败');
                }
            });
        }
        $(function () {
            layui.use('laydate', function () {
                var laydate = layui.laydate;

                //执行一个laydate实例
                laydate.render({
                    elem: '#enrollmentDate' //指定元素
                });
            });
            $('#btn-save').on('click', function () {
                saveStudent();
            });
        });

    </script>
</head>
<body>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="layui-form" style="padding:10px 10px 0px 10px">
            <div class="layui-form-item">
                <label class="layui-form-label">姓:</label>
                <div class="layui-input-block">
                    <input id="lastName" type="text" name="lastName" placeholder="请输入" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">名:</label>
                <div class="layui-input-block">
                    <input id="firstMidName" type="text" name="firstMidName" placeholder="请输入" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">入学时间:</label>
                <div class="layui-input-block">
                    <input id="enrollmentDate" type="text" name="enrollmentDate" placeholder="请输入" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit lay-filter="*" type="button" id="btn-save">立即提交</button>
                    <button type="button" class="layui-btn layui-btn-primary" onclick="closeLayer()">取消</button>
                </div>
            </div>
        </div>
    }
</body>
</html>

ContosoUniversity/Views/Students/Edit.cshtml
@{
    Layout = null;
}

@model ContosoUniversity.Models.Student
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link rel="stylesheet" href="~/lib/layui/css/layui.css">
    <script src="/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="/lib/layui/layui.js" type="text/javascript"></script>
    <script type="text/javascript">
        function LayerMsg(msg) {
            layui.use('layer', function () {
                var layer = layui.layer;
                layer.msg(msg);
            });
        }

        function CloseLayer() {
            layui.use('layer', function () {
                var layer = layui.layer;
                var index = parent.layer.getFrameIndex(window.name);
                parent.layer.close(index);
            });
        }
        function GetStudent() {
            $.ajax({
                type: 'post',
                dataType: 'json',
                data: getParameters(),
                url: '/Students/Edit',
                success: function (res) {
                    if (res.errcode == 0) {
                        BindStudent(res.data);
                    }
                    else {
                        layerMsg('fail');
                    }
                },
                error: function (res) {
                    layerMsg('请求失败');
                }
            });
        }

        function BindStudent(data) {
            $('#lastName').val(data.LastName);
            $('#firstMidName').val(data.FirstMidName);
            $('#enrollmentDate').val(data.EnrollmentDate);
            $('#hid').val(data.ID);
        }

        function GetParameters() {
            var form = $('#__AjaxAntiForgeryForm');
            var token = $('input[name="__RequestVerificationToken"]', form).val();
            var params = {
                __RequestVerificationToken: token,
                ID: $('#hid').val(),
                LastName: $('#lastName').val(),
                FirstMidName: $('#firstMidName').val(),
                EnrollmentDate: $('#enrollmentDate').val()
            };
            return params;
        }

        function SaveStudent() {
            $.ajax({
                type: 'post',
                dataType: 'json',
                data: GetParameters(),
                url: '/Students/Update',
                success: function (res) {
                    if (res.errcode == 0) {
                        LayerMsg('success');
                    }
                    else {
                        LayerMsg('fail');
                    }
                },
                error: function (res) {
                    LayerMsg('请求失败');
                }
            });
        }

        function DateSelectorInit() {
            layui.use('laydate', function () {
                var laydate = layui.laydate;

                //执行一个laydate实例
                laydate.render({
                    elem: '#enrollmentDate' //指定元素
                });
            });
        }

        function PageEventInit() {
            $('#btn-save').on('click', function () {
                SaveStudent();
            });
        }

        $(function () {
            DateSelectorInit();
            PageEventInit();
            //GetStudent();
        });

    </script>
</head>
<body>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("hid",Model.ID,null)
        <input type="hidden" id="hid" />
        <div class="layui-form" style="padding:10px 10px 0px 10px">
            <div class="layui-form-item">
                <label class="layui-form-label">姓:</label>
                <div class="layui-input-block">
                    @Html.TextBox("lastName", Model.LastName, "", new { @class = "layui-input", placeholder = "请输入", autocomplete = "off" })
                    @*<input id="lastName" type="text" name="lastName" placeholder="请输入" autocomplete="off" class="">*@
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">名:</label>
                <div class="layui-input-block">
                    @Html.TextBox("firstMidName", Model.FirstMidName, "", new { @class = "layui-input", placeholder = "请输入", autocomplete = "off" })
                    @*<input id="firstMidName" type="text" name="firstMidName" placeholder="请输入" autocomplete="off" class="layui-input">*@
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">入学时间:</label>
                <div class="layui-input-block">
                    @Html.TextBox("enrollmentDate", Model.EnrollmentDate.ToString("yyyy-MM-dd"), "", new { @class = "layui-input", placeholder = "请输入", autocomplete = "off" })
                    @*<input id="enrollmentDate" type="text" name="enrollmentDate" placeholder="请输入" autocomplete="off" class="layui-input">*@
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">备注:</label>
                <div class="layui-input-block">
                    @Html.TextBox("enrollments", Model.Enrollments, "", new { @class = "layui-input", placeholder = "请输入", autocomplete = "off" })
                    @*<input id="enrollmentDate" type="text" name="enrollmentDate" placeholder="请输入" autocomplete="off" class="layui-input">*@
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit lay-filter="*" type="button" id="btn-save">修改</button>
                    <button type="button" class="layui-btn layui-btn-primary" onclick="CloseLayer()">取消</button>
                </div>
            </div>
        </div>
    }
</body>
</html>

ContosoUniversity/Views/Students/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<!--Student-->
<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">@ViewData["Title"]</div>
        <div class="layui-card-body">
            <div class="layui-btn-group">
                <button class="layui-btn" id="btn-add">增加</button>
                <button class="layui-btn" id="btn-edit">编辑</button>
                <button class="layui-btn" id="btn-del">删除</button>
            </div>
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
</div>

<script type="text/javascript">
    var GlobalParams = {
    };

    function LayerMsg(msg) {
        layui.use('layer', function () {
            var layer = layui.layer;
            layer.msg(msg);
        });
    }

    function ShowCreateContent(url) {
        layui.use('layer', function () {
            var layer = layui.layer;
            layer.open({
                id:'studentCreate',
                type: 2,
                title:'创建学生',
                area: ['700px', '100%'],
                fixed: false, //不固定
                maxmin: false,
                shade: [0.3, '#000'],
                offset: 'r',
                closeBtn: 0,
                shadeClose: false,
                //anim:3,
                content: url
            });
        });
    }

    function LoadTableList() {
        layui.use('table', function () {
            var table = layui.table;
            //第一个实例
            table.render({
                elem: '#demo',
                height: 312,
                id:'id',
                url: '/Students/List', //数据接口
                parseData: function (res) { //res 即为原始返回的数据
                    return {
                        "code": 0, //解析接口状态
                        "msg": '', //解析提示文本
                        "count": res.length, //解析数据长度
                        "data": res //解析数据列表
                    };
                },
                page: true, //开启分页
                cols: [[ //表头
                    { type: 'checkbox' },
                    { field: 'id', title: 'ID', width: 80, sort: true },
                    { field: 'lastName', title: '姓', width: 150 },
                    { field: 'firstMidName', title: '名', width: 150, sort: true },
                    { field: 'enrollmentDate', title: '入学时间', width: 200, sort: true }
                ]]
            });
            GlobalParams['table'] = table;
        });
    }

    function GetTableCheckStatus() {
        var checkStatus;
        //checkStatus=GlobalParams.table.checkStatus('id');
        layui.use('table', function () {
            var table = layui.table;
            checkStatus = table.checkStatus('id');
        });
            return checkStatus;
    }

    function PageEventInit() {
        $('#btn-add').on('click', function () {
            ShowCreateContent('/Students/Create');
        });
        $('#btn-edit').on('click', function () {
            var checkStatus = GetTableCheckStatus();
            if (checkStatus.data.length == 1) {
                ShowCreateContent('/Students/Edit/' + checkStatus.data[0].id);
            }
            else if (checkStatus.data.length > 1) {
                LayerMsg('只能选择一项进行编辑');
            }
            else {
                LayerMsg('请选择一项进行编辑');
            }
        });
    }

    $(function () {
        LoadTableList();
        PageEventInit();
       
});
</script>